CREATE TABLE Products (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PRODUCT_ID INT NOT NULL,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    PRODUCT_PRICE DECIMAL(10, 2) NOT NULL,
    PRODUCT_ARTICLE VARCHAR(100),
    PRODUCT_QUANTITY INT NOT NULL,
    DATE_CREATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IS_HIDDEN TINYINT DEFAULT 0
);


--Здесь я для примера ввел свои значения
INSERT INTO Products (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_ARTICLE, PRODUCT_QUANTITY)
VALUES 
    (1, 'Товар 1', 100.00, 'ART001', 10),
    (2, 'Товар 2', 200.50, 'ART002', 5),
    (3, 'Товар 3', 250.10, 'ART003', 20);
       